server:
  port: ${MS_CUSTOMER_SERVER_PORT:7001}
spring:
  application:
    name: customer
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost}:${ZIPKIN_SERVER_PORT:9411}
  datasource:
    username: ${CUSTOMER_DB_USERNAME:postgres}
    password: ${CUSTOMER_DB_PASSWORD:root}
    url: jdbc:postgresql://${CUSTOMER_DB_SERVER_URL:localhost}:${CUSTOMER_DB_SERVER_PORT:5432}/customer
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    format_sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost}:${EUREKA_SERVER_PORT:8761}/eureka
