server:
  port: ${MS_CUSTOMER_SERVER_PORT:7001}
spring:
  application:
    name: customer
  datasource:
    username: ${CUSTOMER_DB_USERNAME:postgres}
    password: ${CUSTOMER_DB_PASSWORD:root}
    url: jdbc:postgresql://${CUSTOMER_DB_SERVER_URL:postgres}:${CUSTOMER_DB_SERVER_PORT:5432}/customer
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://zipkin}:${ZIPKIN_SERVER_PORT:9411}
  rabbitmq:
    addresses: ${RABBITMQ_SERVER_URL:rabbitmq}:${RABBITMQ_SERVER_PORT:5672}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server}:${EUREKA_SERVER_PORT:8761}/eureka
