server:
  port: ${MS_CUSTOMER_SERVER_PORT:7001}
spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/customer_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetch-registry: true
    register-with-eureka: true
