server:
  port: ${MS_NOTIFICATION_SERVER_PORT:7003}
spring:
  application:
    name: notification
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost}:${ZIPKIN_SERVER_PORT:9411}
  datasource:
    username: ${NOTIFICATION_DB_USERNAME:postgres}
    password: ${NOTIFICATION_DB_PASSWORD:root}
    url: jdbc:postgresql://${NOTIFICATION_DB_SERVER_URL:localhost}:${NOTIFICATION_DB_SERVER_PORT:5432}/notification
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost}:${EUREKA_SERVER_PORT:8761}/eureka


