server:
  port: ${API_GATEWAY_PORT:7004}
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://zipkin}:${ZIPKIN_SERVER_PORT:9411}
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server}:${EUREKA_SERVER_PORT:8761}/eureka
    fetch-registry: true
    register-with-eureka: true
