server:
  port: ${MS_FRAUD_SERVER_PORT:7002}
spring:
  application:
    name: fraud
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/fraud_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost}:${EUREKA_SERVER_PORT:7777}/eureka
    fetch-registry: true
    register-with-eureka: true

